# Generated by Django 5.1.5 on 2025-01-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboro', '0004_transactionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(through='onboro.TransactionRecord', to='onboro.book'),
        ),
    ]
